#!/bin/bash

#find / -name "*.xml*" > XMLFiles.out

#exit

filename="XMLFiles.out"


while read -r line
do
	cat $line | grep "<ags:resource ags:ARN=" >> idsInXML.out
	echo "cat $line | grep \"<ags:resource ags:ARN=\" >> idsInXML.out"
done < "$filename"

echo "Performing cleansing"
sed -i -e 's/<ags:resource ags:ARN="//g' idsInXML.out
sed -i -e 's/">//g' idsInXML.out
echo "Cleansing of file complete"
