#!/bin/bash

echo "I am expected to run after ../findAllIdsRDF/querySPARQL script!"
filename="../findAllIdsRDF/not.out"

echo "Reading output file containing ids not found.."

while read -r line
do
	./performFind $line
done < "$filename"

echo "Done"

